### PR TITLE
My Trees internationalization

### PR DESCRIPTION
**Pull request by huang0h**
## Checklist

- [x] 1. Run `npm run check`
- [x] 2. Run `npm run test`
- [x] 3. Change ClickUp ticket status to "In Review"
- [x] 4. After making the PR, add PR link to ClickUp ticket

## Why

(no ticket)

Continue internationalization work

## This PR

- Internationalization for my trees page (`treePage`) + child components

### CODE REVIEW

**Comment by rymaju** [comment]
@chromium-52 @huang0h Whats the state of this PR?

**Comment by huang0h** [comment]
> @chromium-52 @huang0h Whats the state of this PR?

Just waiting on reviews + approval - @chromium-52 should we merge this now as part of the my trees page redesign, or do we want to put it off until after it's done?

**Review by SurabhiKeesara — APPROVED** [review]
lgtm!

**Review by chromium-52 — APPROVED** [review]
👍 lgtm!!

**Pull request merged**
