### PR TITLE
made basic admin dashboard, access with the /admin route

### PR DESCRIPTION
**Pull request by willmt80**
## Why

[Monday.com Ticket](https://code4community-team.monday.com/boards/702429655/views/12631042/pulses/816272680)

What benefit does this bring to the end user? Or, what benefit does this bring to developers working in the codebase?

The basic UI for admin users to download data and for super admins to add teams

## This PR

Describe the changes required and any implementation choices you made to give context to reviewers.

This PR was just for the UI, user information and routes to get team data have not been set up yet. I made a function to convert a list of key, value pairs to dropdown menu items that can be used once we have real data. I also made the add new admin functionality appear when a superuser boolean value is true, this value can be set in the real application with the user's data

## Screenshots

Provide screenshots of any new components, styling changes, or pages.

admin-dashboard

The colors are still based on the old global theme. once the global style PR is merged the header colors and button style will match the design docs.

## Verification Steps

What steps did you take to verify your changes work? These should be clear enough for someone to be able to clone the branch and follow the steps themselves.

Mostly just UI stuff so I made sure that the component matches the design docs.

### CODE REVIEW

**Comment by florisdobber** [comment]
Haven't reviewed the code, but as a quick note could you replace the add admin team + team member drop down by a text input field. The fields that should be there are new admin email and user password. Maybe phrase those differently and I'll ask Brandon to adjust the designs since you're right, this is what the designs show.

**Review by jackblanc — COMMENTED** [review]
We should to add a field for selecting the role from `Standard`, `Admin`, `SuperAdmin`. `SuperAdmin`s should be allowed to _set_ the privilege level of any user, but they shouldn't be allowed to demote other `SuperAdmin`s.

**Comment by florisdobber** [comment]
> 
> 
> We should to add a field for selecting the role from `Standard`, `Admin`, `SuperAdmin`. `SuperAdmin`s should be allowed to _set_ the privilege level of any user, but they shouldn't be allowed to demote other `SuperAdmin`s.
Super admins can do anything, also demote super admins

**Comment by willmt80** [comment]
I'd like to get the designs nailed down for this before changing this. Sounds like the functionality isn't really adding an admin as much as it is changing a user's admin status.

**Comment by jackblanc** [comment]
@florisdobber did we finalize this?

**Comment by florisdobber** [comment]
> 
> 
> @florisdobber did we finalize this?

Yeah, see fixed design. User roles are standard user, admin, super admin.

**Review by florisdobber — APPROVED** [review]

**Pull request merged**
